### ISSUE TITLE
Review documentation

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-operator#158]
We need guides to define better documentation for:

- Kubernetes installation
- How our controllers behave (deletion etc.)
- SBO documentation - what is the end result of this operator - not clear right now
- Review documentation for any updates that we made to resources (metadata etc.) that weren't reflected in the docs

**Comment by secondsun** [comment]
Include documentation for setting the production/stage environemnt variables. This replaces https://github.com/redhat-developer/app-services-operator/issues/112

**Comment by secondsun** [comment]
WRT connecting to SBO

link to https://github.com/redhat-developer/app-services-cli/blob/main/docs/commands/rhoas_cluster_connect.adoc and the ui and give a few sentences to describe that this is the source of truth for those tools

**Comment by secondsun** [comment]
Add guides repo @wtrocki will link these on this issue

**Comment by secondsun** [comment]
I've been stuck on this a while and haven't made progress, unassigning to regroup.

**Comment by wtrocki** [comment]
@secondsun but who will do it? This was the only item you have been assigned on for couple weeks.
This seems critical from point of view of the operator and currently blocking epic.

**Comment by secondsun** [comment]
I don't know, we can get someone from docs. I'm just not sure what to do with this/where to take it/how to close it. I feel like the docs operator side are done enough for where we are and this can just be closed.

**Comment by wtrocki** [comment]
CC @pmuir

**Comment by secondsun** [comment]
If you have a doc that can be literally copied and pasted then the docs are done, copy paste it, and be done.

**Comment by pmuir** [comment]
@jciroli-rh FYI - this relates to the docs.

I think the next step is to have a writer review what we've got, and see what is missing.

**Comment by pmuir** [comment]
Assigning to @jciroli-rh for next steps.

**Comment by jciroli-rh** [comment]
Assigning to @jbyrne-redhat, who is looking at operator/binding deliverables now.

**Comment by jbyrne-redhat** [comment]
@pmuir @wtrocki @secondsun - Is this the same documentation review task that we're tracking in https://issues.redhat.com/browse/MAKDOC-148? That is, the Operator documentation found [here](https://github.com/redhat-developer/app-services-operator/tree/main/docs)?

**Comment by jbyrne-redhat** [comment]
Also, can you say more about associated user/job stories for this documentation? The sections on Custom Resources, controllers, and API mocks get into a lot of underlying detail for the RHOAS Operator. I wondered how much of this we would want to expose in our upstream and downstream guides.

**Comment by wtrocki** [comment]
We want to have some user stories. Those would be typically technical details used to integrate with operator in cli and openshift and not really part of the end user doc.

The only part that is valid there is installation but needs more work.

We are missing following stories:

- What operator does
- How to use it
   - How to use it CLI
   - How to use it OpenShift
- What is service binding
- Service Binding Service reference

**Comment by wtrocki** [comment]
As for the jira - This is upstream github issue created to  actually write content. We do duplicate issues as community do not have access to jira

**Comment by jbyrne-redhat** [comment]
Thanks for your replies, @wtrocki - they helped to clarify things.

With regards to the missing user stories you describe, I have begun work on defining an outline for a dedicated service binding guide. That guide will address all of the user stories you've outlined above. It helps to know that the Operator documentation developed via this issue is not regarded as end-user doc.

**Comment by wtrocki** [comment]
Also woth checking guides we already have for service binding in guides repo and in this repo as well

**Comment by jbyrne-redhat** [comment]
For the documentation review requested in this issue, I believe the scope is confined to the various Asciidoc files found here: https://github.com/redhat-developer/app-services-operator/tree/main/docs.

I plan to review each of these in turn and open a PR against each one.

**Comment by jbyrne-redhat** [comment]
PR for review of Operator installation procedure: https://github.com/redhat-developer/app-services-operator/pull/221

**Comment by wtrocki** [comment]
Good documentation for similar concepts that can be used as influence

https://aws.amazon.com/partners/servicebroker/
https://github.com/GoogleCloudPlatform/gcp-service-broker
https://crossplane.io/docs/v1.2/concepts/overview.html

**Comment by jbyrne-redhat** [comment]
Thanks, @wtrocki. I'll review those resources for our end-user documentation.

**Comment by jbyrne-redhat** [comment]
For now, however, I'll continue to focus this issue on review of our developer/contributor documentation.

PR for review of the Custom Resource controllers documentation: https://github.com/redhat-developer/app-services-operator/pull/222

**Comment by jbyrne-redhat** [comment]
PR for review of the Custom Resource controllers documentation: https://github.com/redhat-developer/app-services-operator/pull/222

**Comment by jbyrne-redhat** [comment]
PR for review of the Custom Resources documentation: https://github.com/redhat-developer/app-services-operator/pull/225

**Comment by wtrocki** [comment]
FYI. We were explicitly asked to provide documentation for OpenShift UI and operator for OpenShift support team.
Requirement is to provide information about Console client. What it does etc.

**Comment by jbyrne-redhat** [comment]
> FYI. We were explicitly asked to provide documentation for OpenShift UI and operator for OpenShift support team.
> Requirement is to provide information about Console client. What it does etc.

ACK, @wtrocki. Are there new issues for development/review of that additional documentation? 

I believe #158 is now complete according to its original scope - all of our existing documentation has been reviewed and updated.

**Comment by wtrocki** [comment]
Amazing point. Let's close this issue. 

I have created separate issue based on the comment above. 
User documentation will be separate concern:
https://github.com/redhat-developer/app-services-operator/issues/228
