### ISSUE TITLE
Restart operator pod automatically after a specific error threshold is reached

### ISSUE THREAD

**Issue by b1zzu** [redhat-developer/app-services-operator#170]
**Use Case**
After OpenStack and OCP went back the Binding Operator Pod on the cluster was in a "broken" state (it keep throwing java exception to do with the fact that the pod couldn't reach the kubernetes api), but after a simple restart of the operator everything started to work perfectly.. I was therefore thinking that if the operator has a /health endpoint that return a error after a specific error threshold is reached we could combine it with the pod liveness probe and let openshift restart the pod automatically

**How**
?

**Comment by metacosm** [comment]
Let me know if there's anything the sdk could do to make it even easier.

**Comment by secondsun** [comment]
@metacosm  Is there a way to intercept exceptions that happen inside of the operator sdk libraries? IE could I pass a callback to the sdk that gracefully restarts the operator if there's an exception that isn't caught/handled?

**Comment by secondsun** [comment]
@b1zzu Was the operator not doing processing, or just spamming logs?

**Comment by metacosm** [comment]
@secondsun not at the moment… How would that work, though?

**Comment by secondsun** [comment]
@b1zzu Sounds like there may be a bug in the SDK if the connection to k8s drops and the controllers stop getting updates. @metacosm Have you heard of anything like this?

**Comment by secondsun** [comment]
closing in favor of https://github.com/redhat-developer/app-services-operator/issues/182#issuecomment-821513440
