### ISSUE TITLE
Operator workflows are missconfigured

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-operator#177]
I always get email about failed release workflow when creating PR:
![Screenshot 2021-04-15 at 11 37 36](https://user-images.githubusercontent.com/981838/114856420-ff82e100-9dde-11eb-
8b50-a24cc8c1593e.png)

**Comment by secondsun** [comment]
The screenshot didn't upload correctly, can you resent it?

**Comment by wtrocki** [comment]
See failed actions: https://github.com/redhat-developer/app-services-operator/actions

**Comment by wtrocki** [comment]
To be clear - release is triggered and it does commit somehow but fails to:
https://github.com/redhat-developer/app-services-operator/runs/2351910024?check_suite_focus=true

**Comment by wtrocki** [comment]
This is serious issue. I see actual release done 10 days ago from non tag. 
Because of this issue I will disable now release workflow to not accidently release operator

@secondsun

**Comment by wtrocki** [comment]
Trigger was invalid. I have switched to different trigger. Let's see if that will happen.
