### ISSUE TITLE
Watching on resource returns update without updating status

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-operator#179]
This might be some internal Kubernetes api but making the change on the resource kicks in watch - that brings error from resource before it is being updated. Technically we could reset all states to unknown at the beginning of the processing but this will still not reduce flicker. Logging for future consideration

1. Resource exist
2. We update it to get update
3. Watches gets notified by update
4. Operator updates status
5. Second update

Can we avoid 3.

**Comment by secondsun** [comment]
I've noticed this as well, I did a little investigation and it seems like it is some weird internal thing. We'll take it up after summit

**Comment by secondsun** [comment]
@wtrocki I believe this was fixed by changing the refresh property in the console?
