### ISSUE TITLE
Publish the models as github package

### ISSUE THREAD

**Issue by b1zzu** [redhat-developer/app-services-operator#181]
The E2E tests are currently using a models version manually built and pushed in the E2E repo, but if we could publish the model publically we will not have to do it anymore.

I'm proposing GitHub packages because is probably going to be the easiest way, but also maven is fine if we can publish it there

**Comment by b1zzu** [comment]
FYI @secondsun @wtrocki

**Comment by wtrocki** [comment]
Amazing suggestion! Are you blocked/expecting quick resolution for this?

**Comment by b1zzu** [comment]
No no blockers, just want forget it, let's do critical things before :)

**Comment by secondsun** [comment]
like this ? https://github.com/secondsun/app-services-operator/packages/735636

It isn't too hard so if you get blocked we can roll up some hand deployment scripts with a manual version for a fast deployment and then script the proper maven tooling to automatically version the resources.

**Comment by wtrocki** [comment]
Nice - thank you so much GitHub!
Can we reset version to operator version as well.

**Comment by secondsun** [comment]
@wtrocki Yes. We haven't been publishing the files so the versions are basically undefined.

**Comment by wtrocki** [comment]
Done

**Comment by b1zzu** [comment]
@wtrocki can I find it on mvnrepository?

**Comment by wtrocki** [comment]
Depending on the package - example for kafka-management
https://github.com/redhat-developer/app-services-sdk-java/blob/main/packages/kafka-management-sdk/README.md
