### ISSUE TITLE
Operator should not use autolatest branch for both catalog source and other installations 

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-operator#203]
Operator hub catalog rely on autolatest (this means that once we release version of operator we are releasing it straight to the production (users of old version will pull new version).

This is not acceptable as new version could have a different catalog/resources to support making things fail.

We should address this as soon as possible by having specific versions of operator pushed to quay rather than using single tag for everything.

**Comment by secondsun** [comment]
Can you link me in the operatorhub community operators where it is referencing autolatest? Operatorhub is its own catalog.

**Comment by secondsun** [comment]
Our operatorhub manifests are here : https://github.com/operator-framework/community-operators/tree/master/community-operators/rhoas-operator
