### ISSUE TITLE
correct display name of operator

### ISSUE THREAD

**Issue by christianvogt** [redhat-developer/app-services-operator#208]
Shouldn't this be named `Red Hat OpenShift Application Services Operator` where `Red Hat` is 2 separate words:

![image](https://user-images.githubusercontent.com/14068621/116935060-d1512e00-ac33-11eb-939a-70e1ef171312.png)

**Comment by wtrocki** [comment]
Thank you so much for reporting this. This is going to be fixed and released to operator hub today.
