### ISSUE TITLE
Service Registry Integration 

### ISSUE THREAD

**Issue by secondsun** [redhat-developer/app-services-operator#217]
This issue is to capture the work and discussion for creating the service registry integration.  Currently we have identified
 * Refactor the current Kafka Managed Services API to a new package namespace (.kas)
 * Add the SRS Open APIs (.srs)
 * Update ManagedServicesRequest to handle both Managed Kafkas and Service Registry
 * Create ServiceRegistryConnection custom resource
 * Annotate ServiceRegistryConnection with Service Binding annotations

**Comment by secondsun** [comment]
This isue is blocking https://github.com/redhat-developer/app-services-cli/issues/661

**Comment by wtrocki** [comment]
FYI 

Quarkus has frist class support and even very well written guide and example app:

https://quarkus.io/blog/kafka-avro
