### ISSUE TITLE
[Bug] Quickstarts needs to be installed manually by operator rather than included into bundle

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-operator#230]

**Comment by DuncanDoyle** [comment]
@wtrocki What's the status of this one? Quick Starts are not yet installed when installing the operator AFAICT. I'll copy the updated Quick Starts to the Sandbox repo, but it would be nice if those updates were auto-installed by the operator itself.

**Comment by wtrocki** [comment]
Done by @secondsun

**Comment by secondsun** [comment]
@DuncanDoyle QuickStarts are installed, they might not be updated by the operator, I'll 2x check. As an aside, the operatorhub repository changed its format and that has thrown a small spanner into our release scripts, that should be fixed today however.

**Comment by secondsun** [comment]
Installed from operator hub, looks like several consolequickstart objects were made

![image](https://user-images.githubusercontent.com/2413816/128251908-d11107d9-df6d-48a5-a8b8-33b997262775.png)

**Comment by wtrocki** [comment]
<img width="1343" alt="Screenshot 2021-08-05 at 11 44 29" src="https://user-images.githubusercontent.com/981838/128337589-b2b44271-351b-45dd-b8f7-1263b86ffcc9.png">

They are installed properly now. We can remove duplicates from sandbox
