### ISSUE TITLE
Wrong id in the pom

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-operator#254]
Our pom does have openshift.cloud as id where we have registered com.redhat.cloud.

CC @secondsun for clarification

**Comment by secondsun** [comment]
It doesn't matter as we aren't publishing libraries to be consumed as dependencies.

**Comment by wtrocki** [comment]
But should we technically use the same org for all?

**Comment by secondsun** [comment]
Until we publish jar files used by other projects, it doesn't matter. It can be whatever we want.

**Comment by secondsun** [comment]
I would say we should aesthetically use the same org.
