### ISSUE TITLE
Creation of the service account should setup default ACL 

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-operator#260]
When creating a service account now we would need to supply additional ACL rules. 
ACL are supported as a separate calls on specific Kafka instance.

Documentation:
https://github.com/redhat-developer/app-services-sdk-java/blob/main/packages/kafka-instance-sdk/docs/AclsApi.md

### Adding ACL with Kafka connections

When creating a service account we do not know for what we going to use it (current architecture)
so adding new KafkaCR to the openshift cluster should supply ACL (Not service account creation itself)
Once we add service registry to kafka we might need to rethink that architecture

### What rules to add

By default every user gets describe access. 
We need to supply additional roles in order to produce and consume messages. 
Our spec for Kafka probably need to mimick some of the options that user might set for ACL (and use sensible defaults for backwards compatibility) - Not sure if we need that.

### Supporting delete operation 

Do we need to remove ACL when connection is deleted?

### Supporting future services

ACL are custom to Kafka. For services like service registry we will need to use specific API from their backend (Service registry will use simple RBAC API for that)

**Comment by wtrocki** [comment]
What we missing is clear definition of the ACLs we should apply

**Comment by pmuir** [comment]
We have discsused a "shortcut" that's similar for the UI "Give me a service account that can produce and consume" or something like that. We should sync the rules.

**Comment by wtrocki** [comment]
Yes. I'm trying to figure out `"Give me a service account that can produce and consume` for CLI and Operator.
Do we have that somewhere in UI? If not please ping me on PR to take look at this. I have some understanding in Kafka ACL overall but would like to keep the same standard (or even keep this in SDK's to produce consistent keys/permissions across the board

**Comment by pmuir** [comment]
We will try to schedule a discussion as we need input from Kafka folks.

**Comment by secondsun** [comment]
@pmuir Can you schedule it for a US friendly time? After 9 AM.

**Comment by pmuir** [comment]
The default ACLs will be everyone in the org has describe.

**Comment by secondsun** [comment]
@pmuir I don't understand your last comment.

**Comment by wtrocki** [comment]
Closed. Wont do
