### ISSUE TITLE
RHOAS operator installation is having issues in an openshift 4.9 cluster

### ISSUE THREAD

**Issue by sanketpathak** [redhat-developer/app-services-operator#269]
On openshift 4.9 cluster(UI) installation of RHOAS operator is not happening properly. As you can see in the screenshot it's status remains as Pending
![Screenshot from 2021-09-23 20-29-57](https://user-images.githubusercontent.com/10252230/135102545-ed5f96bb-661f-48ea-b18a-82829642ba88.png)

![Screenshot from 2021-09-23 20-32-06](https://user-images.githubusercontent.com/10252230/135103940-6fc3d3a3-1732-4c57-bd3e-fe4a41d1f294.png)

 Here are the pod logs from the cluster for it
 
[rhoas-operator-5965d9df6-rv9cn-rhoas-operator.log](https://github.com/redhat-developer/app-services-operator/files/7244695/rhoas-operator-5965d9df6-rv9cn-rhoas-operator.log)

**Comment by wtrocki** [comment]
Logs shows that Operator fails to connect with Kubernetes API. 
There are numerous issues related to that but we cannot handle this differently on operator side itself. 

We need to establish why this is happening

**Comment by wtrocki** [comment]
We have spent so much time improving overall stability of the connection but issue were related with lack of certificate on the cluster:

```
2021-10-13 18:03:53,456 WARN  [io.fab.kub.cli.dsl.int.WatcherWebSocketListener] (OkHttp https://172.30.0.1/...) Exec Failure: javax.net.ssl.SSLException: Socket closed
```

**Comment by wtrocki** [comment]
Done by @secondsun
