### ISSUE TITLE
Release Operator to Operator Hub

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-operator#54]
Provide set of names labels and ask for verification before submission.
Work on technical requirements. 
Write official description for the operator and ask for the validation

**Comment by secondsun** [comment]
See : https://operatorhub.io/contribute

**Comment by secondsun** [comment]
![image](https://user-images.githubusercontent.com/2413816/114729149-b7e05480-9d0d-11eb-9007-e8ebf6ac6804.png)
Add eexamples

**Comment by secondsun** [comment]
For docs, from operatorhub : 
```
What the managed application is about and where to find more information
The features your Operator and how to use it
Any manual steps required to fulfill pre-requisites for running / installing your Operator
```

**Comment by secondsun** [comment]
Include in description that this requires a cloud.redhat.com account with link.
